### ISSUE TITLE
作者是否可以提供 embed-viewer.js 文件的源码呢？

### ISSUE THREAD

**Issue by lidianhao123** [danielsss/embed-viewer#2]
希望能获取 https://github.com/danielsss/embed-viewer/blob/main/src/templates/embed-viewer.js 文件源码，作者是否可以提供呢？

**Comment by danielsss** [comment]
> 希望能获取 https://github.com/danielsss/embed-viewer/blob/main/src/templates/embed-viewer.js 文件源码，作者是否可以提供呢？

确实不方便提供，但是这些源码以后可能会开源出来.
